# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b44d5c000f74f2dfd32d22b0c0b067c9cc68c4a68d5ebd25c600fbb5ab2eba7a8d00c14ee643fee01159a708db378c135b3b7c6be76d5dceb6a8a4cb8158341

test:
  secret_key_base: 828ed7e8a355e82727ed0734a1ec7dddfb1589f70b9e585669a7f06453cd944b4fd6e0dd19eb5c9972ac557e5e2d1001dd97240efdd3cfe26f7735a0a86c8769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
